# production environment configurations
production:
  proxyEnable: false
  proxyServer: http://113.55.17.4:3128
  configUrl: https://raw.githubusercontent.com/liudonghua123/system_network_proxy_ynu/master/assets/config.yaml
# debug environment configurations
debug:
  proxyEnable: false
  proxyServer: http://113.55.17.4:3128
  configUrl: https://raw.githubusercontent.com/liudonghua123/system_network_proxy_ynu/master/assets/config.yaml