name: Windows-CI

on:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  build:
    runs-on: windows-latest
    if: contains(github.ref, 'tags')
    steps:
      - uses: actions/checkout@v2
      - name: Branch name
        id: branch_name
        run: |
          echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
          echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
        shell: bash

      - uses: actions/setup-java@v1
        with:
          java-version: '8.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'dev'

      - name: Enable windows support
        run: |
          flutter config --enable-windows-desktop

      - name: Build windows
        run: |
          flutter pub get
          flutter build windows

      - name: Copy required Visual C++ redistributables files
        run: |
          cp -r ./resources/windows_c++_redistributables/* ./build/windows/runner/Release/
        shell: bash

      - name: Build setup installer with squirrel.windows
        run: |
          mkdir -p ./squirrel.windows.build/lib/net45/
          cp -r ./build/windows/runner/Release/* ./squirrel.windows.build/lib/net45/
          ./resources/nuget.exe pack ./resources/system_network_proxy.nuspec -BasePath ./squirrel.windows.build -OutputDirectory ./squirrel.windows.build
          ./resources/packages/squirrel.windows.2.0.1/tools/Squirrel.exe --releasify ./squirrel.windows.build/system_network_proxy.1.0.0.nupkg --releaseDir=./squirrel.windows.build-release
        shell: bash

      - name: Prepare release files
        run: |
          7z a -tzip system_network_proxy-windows-x64-${{ steps.branch_name.outputs.SOURCE_NAME }}.zip -r .\build\windows\runner\Release\*

      - uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: system_network_proxy-windows-x64-${{ steps.branch_name.outputs.SOURCE_NAME }}.zip;squirrel.windows.build-release\RELEASES;squirrel.windows.build-release\Setup.exe;squirrel.windows.build-release\Setup.msi;squirrel.windows.build-release\system_network_proxy-1.0.0-full.nupkg
          tags: true
          draft: false
